package com.miui.player.ui.menu.common;

public interface BaseMenuId {
    public static final int ADD_TO_PLAYLIST = 1;
    public static final int ADD_TRACKS = 28;
    public static final int BATCH_SELECTION_MODE = 16;
    public static final int CHILD_MENU_BASE = 33;
    public static final int CORRECT_ID3 = 22;
    public static final int DELETE_ITEM = 10;
    public static final int DOWNLOAD = 17;
    public static final int DOWNLOAD_ALL_TRACK = 27;
    public static final int EDIT_ID3 = 21;
    public static final int EFFECTS_PANEL = 13;
    public static final int FIND_KTV = 29;
    public static final int GOTO_PLAYBACK = 7;
    public static final int GOTO_START = 6;
    public static final int HIGHER_QUALITY_MUSIC = 30;
    public static final int LAST_MENU_ITEM = 100;
    public static final int MEDIA_SCAN = 31;
    public static final int NEW_PLAYLIST = 4;
    public static final int OPEN_URL = 0;
    public static final int PARTY_SHUFFLE = 8;
    public static final int PLAYLIST_SELECTED = 3;
    public static final int PLAY_SELECTION = 5;
    public static final int QUEUE = 12;
    public static final int QUIT = 18;
    public static final int RENAME_ALBUM = 20;
    public static final int RENAME_ARTIST = 19;
    public static final int SCAN_DONE = 11;
    public static final int SEARCH_ALBUM = 25;
    public static final int SEARCH_LYRIC = 23;
    public static final int SEARCH_MUSIC = 32;
    public static final int SETTINGS = 14;
    public static final int SHUFFLE_ALL = 9;
    public static final int SLEEP_MODE = 15;
    public static final int TYPE_BATCH = 3;
    public static final int TYPE_CONTEXT = 1;
    public static final int TYPE_OPTION = 2;
    public static final int USE_AS_RINGTONE = 2;
    public static final int USE_LOCAL_ALBUM = 26;
    public static final int USE_LOCAL_LYRIC = 24;
}
