package com.ushareit.listenit;

import com.google.android.gms.common.api.Status;

public class don<R extends ceg> extends ced<R> {
    private final Status f10095a;

    public Integer mo1271a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void mo1272a(ceh<? super R> com_ushareit_listenit_ceh__super_R) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status m15169b() {
        return this.f10095a;
    }
}
